DROP TABLE users;
DROP TABLE posts;
DROP TABLE post_sents;

CREATE TABLE users (
	USERID		INT				PRIMARY KEY,
	USERNAME	TEXT			UNIQUE
);
CREATE TABLE posts (
    POST_ID     INT             PRIMARY KEY,
	LJ_POST_ID	INT             NOT NULL,
	USERID		INT             NOT NULL,
	POST_TIME	INT				NOT NULL,
	MOOD		INT,
	UNIQUE(LJ_POST_ID, USERID)
);
CREATE TABLE post_sents (
	POST_ID		INT,
	SENT_NUM	INT,
	SENT_TEXT	TEXT			NOT NULL,
	PRIMARY KEY(POST_ID, SENT_NUM)
);

# DROP TABLE sents_word2vec;
# DROP TABLE sents_lstm;
# DROP TABLE word2id;
# DROP TABLE hashes;
# DROP TABLE hashtables_meta;
# DROP TABLE hash_vectors;
#
# CREATE TABLE word2id (
# 	WORD		TEXT			PRIMARY KEY,
# 	WORD_ID		INT				UNIQUE
# );
# CREATE TABLE sents_word2vec (
# 	POST_ID		INT,
# 	SENT_NUM	INT,
# 	SENT_VECTOR	DECIMAL(5,3)[]	NOT NULL,
# 	PRIMARY KEY(POST_ID, SENT_NUM)
# );
# CREATE TABLE sents_lstm (
# 	POST_ID		INT,
# 	SENT_NUM	INT,
# 	SENT_VECTOR	DECIMAL(5,3)[]	NOT NULL,
# 	PRIMARY KEY(POST_ID, SENT_NUM)
# );
# CREATE TABLE hashtables_meta (
# 	ID				INT 		PRIMARY KEY,
# 	VECTOR_MODEL	TEXT 		NOT NULL,
# 	NUM_BITS		INT			NOT NULL
# );
# CREATE TABLE hash_vectors(
# 	TABLE_ID	INT,
# 	VECTOR_ID	INT,
# 	VECTOR		DECIMAL(2,1)[]	NOT NULL,
# 	PRIMARY KEY(TABLE_ID, VECTOR_ID)
# );
# CREATE TABLE hashes (
# 	TABLE_ID	INT,
# 	POST_ID		INT,
# 	SENT_NUM	INT,
# 	HASH 		INT				NOT NULL,
# 	PRIMARY KEY(TABLE_ID, POST_ID, SENT_NUM)
# );
